apiVersion: batch/v1
kind: CronJob
metadata:
  name: rand-num-job
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rand-num-job
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - shuf -i 0-999 -n1
          restartPolicy: OnFailure

